eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      enable: true
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8764
spring:
  application:
    name: service-ribbon
ribbon:
  eager-load:
    clients:
